const IconApk = async (req, res) => {
  console.log(req.get("Host"));
  const host = "45.32.126.16:5000";
  const data = {
    menu: [
      {
        id: 0,
        name: "Pulsa",
        img: "img.jpg",
        jenis: "elektrik",
        filter: true,
        idoperator: ["INDREG", "XLAXIS", "TRIREG", "SMREG", "BYU", "TSELREG"],
        icon: "https://api.lazimpay.com:7000/assetsapk/icon/pulsa.png",
      },

      {
        id: 1,
        name: "Paket Data",
        img: "img.jpg",
        jenis: "elektrik",
        filter: true,
        idoperator: [
          "PDBYU",
          "XBP3K",
          "XBP5K",
          "XBP2K",
          "SMARTUN",
          "XCFLX",
          "AONTRI",
        ],
        icon: "https://api.lazimpay.com:7000/assetsapk/icon/paket-data.png",
      },
      {
        id: 2,
        name: "PLN",
        img: "img.jpg",
        jenis: "spesial-pln",
        idoperator: "PLN",
        kodeproduk: "PLN",
        opendenom: true,
        filter: false,
        icon: "https://api.lazimpay.com:7000/assetsapk/icon/token-pln.png",
      },
      {
        id: 3,
        name: "Game",
        img: "img.jpg",
        jenis: "elektrik",
        filter: false,
        opendenom: false,
        idoperator: ["FFDM", "MLDM", "VGPL"],
        icon: "https://api.lazimpay.com:7000/assetsapk/icon/game.png",
      },
      {
        id: 4,
        name: "Tlpn & SMS",
        img: "img.jpg",
        jenis: "elektrik",
        filter: true,
        opendenom: false,
        idoperator: ["PTDST"],
        icon: "https://api.lazimpay.com:7000/assetsapk/icon/telp-sms.png",
      },
      {
        id: 5,
        name: "Voucher Data",
        img: "img.jpg",
        jenis: "elektrik",
        filter: true,
        opendenom: false,
        idoperator: ["DANA", "OVO", "MAXD", "LINKAJA", "SGC", "SDG"],
        icon: "https://api.lazimpay.com:7000/assetsapk/icon/voucher-data.png",
      },
      {
        id: 6,
        name: "Emoney",
        img: "img.jpg",
        jenis: "elektrik",
        filter: false,
        opendenom: false,
        idoperator: ["DANA", "OVO", "MAXD", "LINKAJA", "SGC", "SDG", "SHOPEE"],
        icon: "https://api.lazimpay.com:7000/assetsapk/icon/e-money.png",
      },
      {
        id: 8,
        name: "Emoney Bebas",
        img: "img.jpg",
        jenis: "transfer-bank",
        filter: false,
        opendenom: true,
        idoperator: "EMONEYBE",
        icon: "https://api.lazimpay.com:7000/assetsapk/icon/transfer-bank.png",
      },
      {
        id: 9,
        name: "Multi Finance",
        img: "img.jpg",
        jenis: "ppob-multiproduk",
        idoperator: "MULFIN",
        opendenom: false,
        filter: false,
        icon: "https://api.lazimpay.com:7000/assetsapk/icon/multi-finance.png",
      },
      {
        id: 10,
        name: "PDAM",
        img: "img.jpg",
        jenis: "ppob-multiproduk",
        opendenom: false,
        idoperator: "PDAM",
        icon: "https://api.lazimpay.com:7000/assetsapk/icon/pdam.png",
      },
      {
        id: 11,
        name: "BPJS",
        img: "img.jpg",
        jenis: "trx-ppob-singgle",
        kodeproduk: "BPJSKS",
        filter: false,
        opendenom: false,
        icon: "https://api.lazimpay.com:7000/assetsapk/icon/bpjs-2.png",
      },
      {
        id: 12,
        name: "HP Pasca",
        img: "img.jpg",
        jenis: "ppob-multiproduk",
        idoperator: "HPPASCA",
        opendenom: false,
        icon: "https://api.lazimpay.com:7000/assetsapk/icon/hp-pascabayar.png",
      },
      {
        id: 13,
        name: "Cek Omni",
        img: "img.jpg",
        jenis: "webview",
        idoperator: 239,
        url: "https://www.telkomsel.com/shops/channel/o2o?utm_source=wec&utm_medium=qr&utm_campaign=omni-outlet&payment=outlet",
        icon: "https://api.lazimpay.com:7000/assetsapk/icon/pulsa.png",
      },
      {
        id: 13,
        name: "Bayar Omni",
        img: "img.jpg",
        jenis: "trx-ppob-singgle",
        kodeproduk: "OMNI",
        filter: false,
        icon: "https://api.lazimpay.com:7000/assetsapk/icon/pulsa.png",
      },
      {
        id: 14,
        name: "Indihome",
        img: "img.jpg",
        jenis: "trx-ppob-singgle",
        kodeproduk: "HOME",
        filter: false,
        icon: "https://api.lazimpay.com:7000/assetsapk/icon/indihome.png",
      },
      {
        id: 14,
        name: "Transfer Bank",
        img: "img.jpg",
        jenis: "ppob-multiproduk",
        idoperator: "TFB",
        opendenom: true,
        filter: false,
        icon: "https://api.lazimpay.com:7000/assetsapk/icon/transfer-bank.png",
      },
      {
        id: 9,
        name: "Produksi",
        img: "img.jpg",
        jenis: "produksi-voucher",
        idoperator: ["AVA", "ACTTRI"],
        filter: false,
        icon: "https://api.lazimpay.com:7000/assetsapk/icon/voucher-data.png",
      },
    ],
    banner: [
      {
        id: 0,
        title: "Xl data Murah buktikan murahnya",
        imgurl:
          "https://fazz.com/id/wp-content/uploads/sites/3/2022/10/BLOG-FazzAgen_XLDANAXIS.jpg",
      },
      {
        id: 1,
        title: "Promo Paket Data indosat ",
        imgurl:
          "https://blog.unitedtronik.co.id/wp-content/uploads/2019/08/050819_V_FISIK_ISAT.jpg",
      },
      {
        id: 2,
        title: "Promo Ramadan by one get One",
        imgurl:
          "https://tri.co.id/image/files/20220308webrejekigercepmaretbahasadesk.jpg",
      },
    ],
    runningteks: {
      id: 0,
      teks: "selamat datanga, customer serivice hanya di 085695662466",
    },
    menufavorit: [
      {
        id: 1,
        name: "Transfer",
        img: "img.jpg",
        jenis: "transfer-bank",
        filter: false,
        idoperator: "TFB",
        icon: "https://api.lazimpay.com:7000/assetsapk/icon/transfer-bank.png",
      },
      {
        id: 2,
        name: "Pulsa",
        img: "img.jpg",
        jenis: "elektrik",
        filter: true,
        idoperator: ["INDREG", "XLAXIS", "TRIREG", "SMREG", "BYU", "TSELREG"],
        icon: "https://api.lazimpay.com:7000/assetsapk/icon/pulsa.png",
      },
      {
        id: 3,
        name: "Emoney",
        img: "img.jpg",
        jenis: "elektrik",
        filter: false,
        idoperator: ["DANA", "OVO", "MAXD", "LINKAJA", "SGC", "SDG", "SHOPEE"],
        icon: "https://api.lazimpay.com:7000/assetsapk/icon/e-money.png",
      },
      {
        id: 4,
        name: "Topup",
        img: "img.jpg",
        jenis: "topup-saldo",
        filter: false,
        idoperator: 110,
        icon: "https://api.lazimpay.com:7000/assetsapk/icon/deposit.png",
      },
    ],
  };

  res.json(data);
};

module.exports = IconApk;
